### ISSUE TITLE
Retrieve video data

### ISSUE THREAD

**Issue by aproni34f** [vimeo/vimeo.php#105]
I have an issue retrieving video info with api. I have generated my access data by creating new application in https://developer.vimeo.com/apps

I ma using Vimeo library from here: https://github.com/vimeo/vimeo.php

Here is my code:

`<?php

```
$key= 'MY_KEY';
$secret = 'MY_SECRET';
$token = 'MY_TOKEN';
$path = '7674096';

require("../autoload.php");
use Vimeo\Vimeo;
$vimeo = new Vimeo($key, $secret, $token);

//Get a video - https://developer.vimeo.com/api/playground/videos/{video_id}
$result = $vimeo->request("/videos/$path", array(
                                        'fields' =>     'uri,name,description,duration,width,height,privacy,pictures.sizes'
                                        ));
echo json_encode($result);
```

?>`

I get null results, and I dont know why, here is test page:

http://accwestcoast.azurewebsites.net/main/vimeo3/src/vimeo_data.php

**Comment by Dashron** [comment]
Theoretically any status code of 0 is supposed to hit this logic: https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L151-L155 which rewrites it to an exception with more details.

Are you using the most up to date version of the library? A status code of 0 usually means that the underlying PHP networking library (in this case php curl) wasn't able to make the request at all.

This could be due to certificate issues, or networking problems, and the logic I linked above will help us get to the bottom of the problem.

**Comment by agilefox** [comment]
There has been no response on this for 4 months. Any reason to keep it open?

**Comment by Dashron** [comment]
@aproni34f feel free to reopen this if you have more questions!
