### ISSUE TITLE
php 5.6 compatible version?

### ISSUE THREAD

**Issue by lozeone** [vimeo/vimeo.php#192]
It appears that this only works with php 7. is there a version compatible with 5.6 out there?

I get:
Parse error: syntax error, unexpected ':', expecting ';' or '{' in vimeo\src\Vimeo\Vimeo.php on line 88
 when trying to use it with 5.6

thanks.

**Comment by tommypenner** [comment]
@lozeone v2.0.5 was the last version to support PHP <7.1: https://github.com/vimeo/vimeo.php/releases/tag/2.0.5

Note that we had to drop PHP <7.1 support because a dependency no longer supported it. If you're using the library to upload larger video files, we strongly recommend using v3.0 or newer of the library; v2.0.5 may have trouble uploading larger files (see the PR https://github.com/vimeo/vimeo.php/pull/186)

**Comment by lozeone** [comment]
All I am trying to do is grab the thumbnail of a private video, which does not work any longer using oembed (it used to). Will v2.0.5 work for that?

**Comment by tommypenner** [comment]
@lozeone If the video has domain-level privacy, you must include a `Referer` header in your oEmbed request with the value set to a domain you have whitelisted. Here's an example oEmbed request for a video with domain-level privacy expressed as a curl:
```
curl -X GET 'https://vimeo.com/api/oembed.json?url=https://vimeo.com/307074610' -H 'Referer: https://player.vimeo.com'
```

If you have any other questions unrelated to the PHP library, contact Vimeo here: https://vimeo.com/help/contact

**Comment by lozeone** [comment]
Thank you so much @tommypenner I could not find that documented anywhere. You are a life saver.

**Comment by tommypenner** [comment]
@lozeone You're welcome! We'll have improved documentation around that privacy type and oEmbed soon.
