### ISSUE TITLE
Get URL of an unlisted video 

### ISSUE THREAD

**Issue by TaktakTaktouk** [vimeo/vimeo.php#198]
Is there any way to get the URL of unlisted video with the API? I know its take this format:
https://vimeo.com/id/code so how can I get the "code" with the API?

**Comment by tommypenner** [comment]
You can only get that full unlisted URL (`vimeo.com/[video_id]/[hash]`) if you are the owner of the video, or if you already have that `[hash]` value. 

As the video owner, the full unlisted URL is returned as the `"link"` property when making a request to `GET https://api.vimeo.com/videos/[video_id]` -- the `[hash]` value is not required in the request uri because you own the video.

As another user, you need the unlisted hash to get the video's metadata. The unlisted hash is appended to the uri like this: `GET https://api.vimeo.com/videos/[video_id]:[hash]`. When authenticating as another user or with a client_credentials token, It is not possible to get the video's full unlisted URL without prior knowledge of the `[hash]` value.
