### ISSUE TITLE
Videos with privacy setting 'Hide from vimeo.com' are not being listed in GET/channels/{channel_id}/videos.   

### ISSUE THREAD

**Issue by ronlinet** [vimeo/vimeo.php#200]
I can add hidden videos to any channel but they are not being returned by API. 
It is not the same case with Albums or Portfolios which are correctly listing the videos even if they are hidden from vimeo.com.  

Steps to reproduce. 
1. Create video with a privacy level 'Hide this video from vimeo.com'
2. Add the video to a channel.     
3. Try to extract the video from the channel with an API call. 
`        $vimeo =  Vimeo::request('/channels/' . $channelId . '/videos', ['per_page' => 10], 'GET');`

OUTPUT  
The video will be missing from the API output yet you can bring the video back to the output by changing its privacy level to 'Can be watched by anyone'. 

There is no such an issue with Portfolio or Albums where API returns all videos regardless of privacy settings.

Is it by design or we deal with a bug?

If it bug it should be fixed ... 
If it is by design it is miss-leading because I am trying with this setting to hide the video from vimeo.com and not from my API / website.

**Comment by tommypenner** [comment]
I tried following your reproduction steps but on step 2 the video is never added to the channel, which is expected behavior.

Videos with "Hide from vimeo.com" privacy (referred to in the API with`"privacy.view":"disable"`), cannot be added to a Channel or Group (see here: https://vimeo.zendesk.com/hc/en-us/articles/224817847-Privacy-settings-overview).

If a video has already been added to a Channel or Group, setting the video's privacy to "Hide from vimeo.com" will remove it from that Channel or Group.
