### ISSUE TITLE
Vimeo : Refund My money back 

### ISSUE THREAD

**Issue by 3li3bdalla** [vimeo/vimeo.php#226]
I make a trial  account for one month in Vimeo, yesterday Vimeo server made auto-renew for 1 year,
in their terms they say that you have the ability to refund your money back within 30 days if 
your plan is plus for 1 year

i made email for them asking for refund, they replay for me

Unfortunately, because we have a cancellation period, we are unable to refund this payment. If auto-renewal is not turned off within the trial period, then your account is charged per the terms and conditions of the free-trial, listed at check out.

**Comment by VianaSLV** [comment]
Hi there!
I'm going through the same. Did manage to solve the issue?
Thanks!

**Comment by 3li3bdalla** [comment]
Yes they refund my Money back after I recontact them , I checked there terms And I found 

"Automatic Renewal: To the extent permitted by applicable law, subscriptions automatically renew at the end of each subscription period unless cancelled beforehand. Monthly plans renew for 30-day periods. Annual plans renew for one-year periods. You must pay the annual or monthly fee (plus any taxes) when each renewal period starts. Unused storage, bandwidth, and other usage limits do not roll over."

Then I say :
here (. Monthly plans renew for 30-day periods) and my plan was for one month only


here they say they gonna refund the money back 

just contact them and tell them you read all terms and there is no term make you unable to refund your money back

**Comment by VianaSLV** [comment]
Thanks for replying!
I've tried to contact them several times, but they don't answer me.
They renewed my plan for one year, that's 1400 in the currency from my country, I'm screwed. Let's hope it works. Thanks!

**Comment by SiranyaLarksukthom** [comment]
Hi VianaSLV,

I faced the same issue to you.
Did you get your refund?

I was charged for auto-renew for yearly and it’s over the period refundable. 
What should I do? I just realized that I was charged in my credit card after day 33.

And support team said that....
Refund Policy: Subject to the terms hereof, Self-Serve subscribers who purchase plans directly from Vimeo may cancel and receive a full refund of their initial purchase within thirty (30) days after purchasing an annual plan and five (5) days after purchasing a monthly plan. 

could you please suggest me?
Thank you.

**Comment by VianaSLV** [comment]
Hi there!
I wrote them many times. Eventually, they answered me and said they would refund me. Make sure you cancel the service ASAP and prove you haven't used it. You can send screenshots. I'm sorry, I don't recall the details, all I remember is that they were kind and willing to help, but they took a long time to answer me. Hope it works out well for you too!

**Comment by linojalexander** [comment]
Hello everyone, Today i faced the same issue.. How could i contact vimeo? can you please provide the customer care/support no..

**Comment by SiranyaLarksukthom** [comment]
> Hello everyone, Today i faced the same issue.. How could i contact vimeo? can you please provide the customer care/support no..

———————————————————————-
hi, please see my message send to them.


Hi Team,As I mentioned this shouldn't auto-renewed yearly, this is not fair. it should be auto-renewed monthly instead. I can pay the amount you charge for this month but for the rest, I would like to get my money back.you can charge me the pro-rate but I can't pay the plus membership till March 6, 2022. Please return my money by May 2021 - March 2022. Or should I delete the account in Vimeo and you can pay me back?I have read all terms and there is no term that makes me unable to refund my money back because I don't want to use Vimeo anymore if things go like this. | Siranya LarksukthomApr 25, 2021, 10:49 AM EDT Hi Team,As I mentioned this shouldn't auto-renewed yearly, this is not fair. it should be auto-renewed monthly instead. I can pay the amount you charge for this month but for the rest, I would like to get my money back.you can charge me the pro-rate but I can't pay the plus membership till March 6, 2022. Please return my money by May 2021 - March 2022. Or should I delete the account in Vimeo and you can pay me back?I have read all terms and there is no term that makes me unable to refund my money back because I don't want to use Vimeo anymore if things go like this.
-- | --
Siranya LarksukthomApr 25, 2021, 10:49 AM EDT Hi Team,As I mentioned this shouldn't auto-renewed yearly, this is not fair. it should be auto-renewed monthly instead. I can pay the amount you charge for this month but for the rest, I would like to get my money back.you can charge me the pro-rate but I can't pay the plus membership till March 6, 2022. Please return my money by May 2021 - March 2022. Or should I delete the account in Vimeo and you can pay me back?I have read all terms and there is no term that makes me unable to refund my money back because I don't want to use Vimeo anymore if things go like this.

**Comment by linojalexander** [comment]
Did you got any response/refund?

**Comment by linojalexander** [comment]
Hello please, somebody give me an answer.. Are you all contacted vimeo through mails. did they refunded the yearly charge?
