### ISSUE TITLE
MY Code is working perfect on local host but its showing curl error on live sever.

### ISSUE THREAD

**Issue by sandeep-ed** [vimeo/vimeo.php#268]
Vimeo\Exceptions\VimeoUploadException Object ( [message:protected] => cURL error 2: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [string:Exception:private] => [code:protected] => 0 [file:protected] => /home/public_html/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php [line:protected] => 610

**Comment by nyavo** [comment]
@elitedigitaltech This is surely due to the `ankitpokhrel/tus-php` cache folder.
This bundle create cache at `vendor/ankitpokhrel/tus-php/.cache`, that is most of the time not writable. So, they are unable to get the tus url and the upload fails.
I have the same issue but in different way and I analyzed the sdk code step by step since 3 days.
The only solution for now is to manage the ACL for this cache folder.

**Comment by aaronm67** [comment]
You can see instructions here: https://github.com/vimeo/vimeo.php/pull/308 for using a custom cache folder.
